server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}

logging:
  level:
    root: INFO
    com.example.dogmiddleware: INFO
