server:
  port: ${SERVER_PORT:8081}

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}

logging:
  file:
    name: logs/dog-middleware-prod.log
  level:
    root: WARN
    com.example.dogmiddleware: INFO